### ISSUE TITLE
Add logging to the gRPC API

### ISSUE THREAD

**Issue by dghubble** [poseidon/matchbox#256]
Log Profile, Group, and Ignition creates and updates.

**Comment by danehans** [comment]
@dghubble if you have not started this work, do you mind if I take it on?

**Comment by dghubble** [comment]
Sure, you're welcome to take a crack at it. Have a look at the `http` logging for reference and keep it scoped to `rpc`. Package `server` should more appropriately be called `core` or something and probably shouldn't handle logging.

**Comment by danehans** [comment]
@dghubble I'll go at it. Thanks for the guidance and I'll ping you with any questions.

**Comment by dghubble** [comment]
@danehans any drafts on this or did something else come up?

**Comment by danehans** [comment]
@dghubble I apologize, I have not had time to work on this.

**Comment by dghubble** [comment]
np
