### ISSUE TITLE
http/ipxe.go logs "No matching profile" when there is no matching group

### ISSUE THREAD

**Issue by ghost** [poseidon/matchbox#303]
`http/ipxe.go` logs "No matching profile", but it appears that it was not even able to find an appropriate group. A missing profile is of course among the effects of a missing group, but having no information that the group is also missing makes this case hard to debug.

**Comment by dghubble** [comment]
Ah, I remember this one - it requires a small refactor to tease apart which file is actually malformed and didn't make it in v0.4.0.

**Comment by urzds** [comment]
Related: #302
