### ISSUE TITLE
Make endpoints available from {{.request.endpoint.$endpoint}}

### ISSUE THREAD

**Issue by rothgar** [poseidon/matchbox#319]
I tend to use additional endpoints enough that it would be very useful if the {{ .request }} variable had the default endpoints already available from the URL that was requested.

Examples would be

{{ .request.endpoint.ignition }}
{{ .request.endpoint.cloud }}
{{ .request.endpoint.metadata }}

This way as new endpoints are added (generic, kickstart, etc.) I wouldn't need to make sure I add that metadata to all of my groups and instead can just use the ones that already exist.

**Comment by dghubble** [comment]
Sounds like:

You'd like to start bootcfg with knowledge of its own resolvable name (bootcfg.example.com) and ports and make that available in template variables to increase portability of the Fuze configs. So `{{ .request.endpoint.ignition }}` expands to `http://bootcfg.example.com:8080/ignition`.

Related to #164
