### ISSUE TITLE
Show how to use Ignition append/replace

### ISSUE THREAD

**Issue by dghubble** [poseidon/matchbox#322]
Here is a PR which shows a quick example (not suitable for merging): #320
- Run etcd example
- http://172.15.0.2:8080/ignition?mac=52:54:00:a1:9c:ae

```
{
  "ignition": {
    "version": "2.0.0",
    "config": {
      "append": [
        {
          "source": "http://172.15.0.2:8080/ignition?profile=authkeys",
          "verification": {}
        }
      ]
    }
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "name": "etcd2.service",
        "enable": true,
        "dropins": [
          {
            "name": "40-etcd-cluster.conf",
            "contents": "[Service]\nEnvironment=\"ETCD_NAME=node1\"\nEnvironment=\"ETCD_ADVERTISE_CLIENT_URLS=http://node1.example.com:2379\"\nEnvironment=\"ETCD_INITIAL_ADVERTISE_PEER_URLS=http://node1.example.com:2380\"\nEnvironment=\"ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379\"\nEnvironment=\"ETCD_LISTEN_PEER_URLS=http://node1.example.com:2380\"\nEnvironment=\"ETCD_INITIAL_CLUSTER=node1=http://node1.example.com:2380,node2=http://node2.example.com:2380,node3=http://node3.example.com:2380\"\nEnvironment=\"ETCD_STRICT_RECONFIG_CHECK=true\"\n"
          }
        ]
      }
    ]
  },
  "networkd": {},
  "passwd": {}
}
```
- http://172.15.0.2:8080/ignition?profile=authkeys

```
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {},
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt3BebCHqnSsgpLjo4kVvyfY/z2BS8t27r/7du+O2pb4xYkr7n+KFpbOz523vMTpQ+o1jY4u4TgexglyT9nqasWgLOvo1qjD1agHme8LlTPQSk07rXqOB85Uq5p7ig2zoOejF6qXhcc3n1c7+HkxHrgpBENjLVHOBpzPBIAHkAGaZcl07OCqbsG5yxqEmSGiAlh/IiUVOZgdDMaGjCRFy0wk0mQaGD66DmnFc1H5CzcPjsxr0qO65e7lTGsE930KkO1Vc+RHCVwvhdXs+c2NhJ2/3740Kpes9n1/YullaWZUzlCPDXtRuy6JRbFbvy39JUgHWGWzB3d+3f8oJ/N4qZ"
        ]
      }
    ]
  }
}
```

Initial report from @rothgar on #coreos IRC Aug 18, 2016.

**Comment by rothgar** [comment]
Thank you for the examples. I tried this with some of my config and it appears to work when the system is running in ram (install-reboot example) but if I try to use append with coreos-install ignition the system fails to start (emergency shell)

I could be doing something wrong but I'm copy/pasting a known working ignition template (install-reboot.yaml) and then using it in k8s-worker/master ignition it doesn't work.

**Comment by crawford** [comment]
Do you have the logs from the failure? In both instances, Ignition runs from the initramfs on the first boot, so it shouldn't matter what mechanism you use to install.

**Comment by rothgar** [comment]
@crawford is there an easy way to pull logs from a system in an emergency shell?

**Comment by crawford** [comment]
`journalctl -t ignition --no-pager`

**Comment by rothgar** [comment]
It appears my problem is either the host is not online or it cannot resolve the bootcfg hostname in DNS (what it looks like to me). Here's the error. Some is cut off because I didn't scroll over at the console (replaced with ???)

failed to fetch config: Get http://bootcfg:8080/ignition?profile=authkeys: dial tcp: lookup bootcfg on [::1]:53: read u??? [::1]:50418->[::1]:53: read: connection refused

**Comment by dghubble** [comment]
The name `bootcfg` TLD is supposed to resolve to bootcfg on your local network?

**Comment by rothgar** [comment]
It does (usually) that's what I've been using. It only seems to break when I do an install and the installation ignition has an append that uses the bootcfg for the url. I could try with an ip address to check if it's a network problem or dns problem.

**Comment by crawford** [comment]
Which version of Ignition is this? It should try multiple times. Can you grab the full Ignition log?

**Comment by rothgar** [comment]
I have no way to pull the logs off the host (that I know of) because it's in an emergency shell with no ssh access. I'll have to look again if network is active because I should be able to push the log to a host. It's physically located in a data center though so I'll need to make time to go try.

**Comment by crawford** [comment]
Do you have SOL access? If Ignition attempted to run, the network should be up (or coming up). I don't think netcat or curl are available in the initramfs though. We have been kicking around the idea of having Ignition optionally POST logs to an endpoint.

**Comment by rothgar** [comment]
Just for anyone else who might find this page. @crawford pointed me to the bug I was hitting coreos/bugs#1455 It should be fixed in this weeks alpha release.
