### ISSUE TITLE
Add Fedora/Centos Install examples

### ISSUE THREAD

**Issue by dghubble** [poseidon/matchbox#525]
Finish the partially complete examples which use Matchbox to network boot and install Fedora/CentOS nodes and do a disk install. This does not provision a useful cluster like the Container Linux examples, but its a starting point.

**Comment by nsaustin** [comment]
Agreed. I just tried installing matchbox onto CentOS and the instructions were either unclear or didn't work.

**Comment by nsaustin** [comment]
FYI - I was able to get it working, but it wasn't obvious from the instructions that the systemd copied service was "matchbox-local" and not just "matchbox", therefore a systemctl "start matchbox-local" is what is needed to be executed to start the service

**Comment by dghubble** [comment]
Hm, I meant for this issue to track adding examples which network boot and install Fedora **nodes**. Let's move the discussion of installing matchbox on Centos to a separate issue.

**Comment by dghubble** [comment]
Matchbox's support for [generic templates](https://github.com/coreos/bugs/issues/2001) has been used by projects to serve cloud-init and kickstart files to PXE booted clusters. For example, it was used to power [Fedora Atomic](https://github.com/poseidon/typhoon/tree/ca18fab5f0eff887b4d92c6f62b547fb70278aad/bare-metal/fedora-atomic/kubernetes) clusters in Typhoon for a time (though Atomic is deprecated now).

Closing this since serving arbitrary configs (without any checks) works. At the moment, I'm not trying to collect any more examples however, maintaining even just the current examples have taken up more time than the core project (e.g. https://github.com/poseidon/matchbox/pull/759)
