### ISSUE TITLE
CentOS 7 RPM availability

### ISSUE THREAD

**Issue by dghubble** [poseidon/matchbox#550]
Moving question from #525

> Agreed. I just tried installing matchbox onto CentOS and the instructions were either unclear or didn't work.
Example: https://coreos.com/matchbox/docs/latest/deployment.html#rpm-based-distro
RPM-based distro
On an RPM-based provisioner, install the matchbox RPM from the Copr repository using dnf or yum.
dnf copr enable @CoreOS/matchbox
dnf install matchbox
CentOS is an RPM-based distro but it doesn't use dnf. What are the yum commands needed?
Thanks!

> FYI - I was able to get it working, but it wasn't obvious from the instructions that the systemd copied service was "matchbox-local" and not just "matchbox", therefore a systemctl "start matchbox-local" is what is needed to be executed to start the service

cc @nsaustin

**Comment by dghubble** [comment]
Good point. In the past, Matchbox's Copr repo used to provide a CentOS 7 RPM which could be installed via `yum`. Matchbox (as of v0.5.0) requires Go 1.7 or higher and CentOS comes with Go 1.6. The CentOS RPM was dropped.

Short term, our docs should only mention `dnf` as only Fedora 24 and 25 are new enough. Instead, downloading a release binary and following the instructions for "general linux" is the best option for CentOS.

Longer term, I'd like to improve this story for those using CentOS.

**Comment by brianredbeard** [comment]
This can be built on top of CentOS/RHEL using Software Collections.  We could potentially make that repo a `BuildRequires` option in the spec.
