### ISSUE TITLE
shield ignition string 

### ISSUE THREAD

**Issue by beatlejuse** [poseidon/matchbox#707]
please help me!
how to shield this string in ignition:
"legendFormat": "{{ instance }}",

i get this message in logs:
matchbox    | time="2018-04-26T15:05:00Z" level=error msg="error parsing template: template: :3182: function \"instance\" not defined"

I need to leave this line unchanged, so the machbox doesn't try to look for a variable with that name

**Comment by sdemos** [comment]
Sorry for the late response! Matchbox runs go templating on the config passed to it. Based on your error message, it looks like the templating is picking up your `"{{ instance }}"` line and then failing to template it. If what you want to do is keep that string exactly and not have matchbox stomp on it with go templating, try something like `{{"{{ instance }}"}}` so go just outputs the string that was given. More information here - https://github.com/coreos/container-linux-update-operator/pull/176
