### ISSUE TITLE
Ubuntu dnsmaq docker port 53: Address in use

### ISSUE THREAD

**Issue by 1oglop1** [poseidon/matchbox#708]
Hi
My Setup:

Host-OS: Ubuntu 18.04 (VMhost, docker Host)
VMs: Virtualbox VMs with bridged networking linked to VM host.

I have problems running the docker container on ubuntu and it seems that problem is caused by `--net=host`

Ubuntu desktop is running instance of dnsmasq to help with name resolution and `/ect/resolf.conf` points to localhost

`/etc/resolv.conf` file
```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "systemd-resolve --status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
search home
```

Then when I run the container, I get an error:

`dnsmasq: failed to create listening socket for port 53: Address in use`

I tried to edit `/etc/systemd/resolved.conf` with `DNSStubListener=no` - this has prevented the error above but then all dns calls were routed to the container which could not resolve them and then I could not browse the Internet.

**Comment by 1oglop1** [comment]
After Some time I found an workaround to set as
`DNSStubListener=udp`
Is there any way to prevent this to happen in dnsmasq or container config?

**Comment by dghubble** [comment]
If you're just developing with the QEMU/KVM examples, the `quay.io/poseidon/dnsmasq` container just needs to be running on the docker bridge, not mapped to the host. No need for `--net=host`. The [devnet](https://github.com/poseidon/matchbox/blob/908e89c3a114295e87a64d42d1699aa9c97ebf9a/scripts/devnet#L180) script doesn't use it. 

Other docs refer to running `quay.io/poseidon/dnsmasq` on a server as a production DNS forwarder and _do_ use port 53. If its already in-use, look at what's using it - it may be an earlier dnsmasq container you've forgotten or another DNS service.
