### ISSUE TITLE
dnsmasq image out of date, containing security issues - most likely many others as well

### ISSUE THREAD

**Issue by shoeper** [poseidon/matchbox#712]
The dnsmasq image has been last build in novemver 2017, older tags even earlier. The dependency alpine:3.6 has been updated several times in the meantime, thus all tags need a rebuild to fix the security vulnerabilities.

Most likely this also effects many other images provided in here.

**Comment by robinsondan87** [comment]
It would also be beneficial to us to upgrade dnsmasq image to something that is newer, we see random ipxe hanging issues which apparently are resolved in later versions of dnsmasq

**Comment by dghubble** [comment]
As per the coreos-user's repo move announcement, the dnsmasq image will now be published under `quay.io/poseidon/dnsmasq` along with Matchbox.

There is a new mechanism to build it via Travis from pushes to a `dnsmasq` branch, but tag images by the repo SHA from which they were produced (no overriding). 

* https://quay.io/repository/poseidon/dnsmasq?tab=tags

**Comment by dghubble** [comment]
Related: 

* https://github.com/poseidon/matchbox/pull/742
* https://github.com/poseidon/matchbox/commit/f4623c508ff3fbc467285de1ede61126624b91ac

**Comment by shoeper** [comment]
The image needs to be rebuild when the base image has been updated as well. Otherwise security issues are going to accumulate.

**Comment by dghubble** [comment]
The based image was already bumped, it's in the links above.

**Comment by shoeper** [comment]
That's not enough. The base image can still change and in that case this image needs a rebuild as well.

**Comment by dghubble** [comment]
I know what your point is, but I'm not planning to take on automated builds.

Prior coreos/dnsmasq images were built by me manually. Now there's a nicer way to bump them when there are significant bumps to alpine. Its sufficient to power the Matchbox examples which use the dnsmasq image in local QEMU/KVM.
