### ISSUE TITLE
Issue on bear metal with stock bootkube example

### ISSUE THREAD

**Issue by richard-chivers** [poseidon/matchbox#719]
Hi,

We are having an issue where we don't seem to be able to bootstrap a cluster using the default examples.

We are following the non terraform example https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md

What happens is that it seems to get stuck in a loop looking for flannel specifically:

`Sep 22 07:06:38 k81.hq-kube.com kubelet-wrapper[2248]: W0922 07:06:38.234612    2248 cni.go:196] Unable to update cni config: No networks found in /etc/kubernetes/cni/net.d
Sep 22 07:06:38 k81.hq-kube.com kubelet-wrapper[2248]: E0922 07:06:38.234732    2248 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

My hunch is that there is an issue with etcd. to attempt to proove this i am trying to run the following command:

`etcdctl --endpoints=https://k81.hq-kube.com:2379  get cluster-health`

After having set the environment variables:

`
export ETCDCTL_API=3
`

What i recieve is an error Error: context deadline exceeded.

So from here i add the debug flag --debug

Which tells me 

`etcdctl --endpoints=https://k81.hq-kube.com:2379 get cluster-health --debug
ETCDCTL_CACERT=
ETCDCTL_CERT=
ETCDCTL_COMMAND_TIMEOUT=5s
ETCDCTL_DEBUG=true
ETCDCTL_DIAL_TIMEOUT=2s
ETCDCTL_DISCOVERY_SRV=
ETCDCTL_ENDPOINTS=[https://k81.hq-kube.com:2379]
ETCDCTL_HEX=false
ETCDCTL_INSECURE_DISCOVERY=true
ETCDCTL_INSECURE_SKIP_TLS_VERIFY=false
ETCDCTL_INSECURE_TRANSPORT=true
ETCDCTL_KEEPALIVE_TIME=2s
ETCDCTL_KEEPALIVE_TIMEOUT=6s
ETCDCTL_KEY=
ETCDCTL_USER=
ETCDCTL_WRITE_OUT=simple
INFO: 2018/09/22 07:10:39 ccBalancerWrapper: updating state and picker called by balancer: IDLE, 0xc42015cc00
INFO: 2018/09/22 07:10:39 dialing to target with scheme: ""
INFO: 2018/09/22 07:10:39 could not get resolver for scheme: ""
INFO: 2018/09/22 07:10:39 balancerWrapper: is pickfirst: false
INFO: 2018/09/22 07:10:39 balancerWrapper: got update addr from Notify: [{k81.hq-kube.com:2379 <nil>}]
INFO: 2018/09/22 07:10:39 ccBalancerWrapper: new subconn: [{k81.hq-kube.com:2379 0  <nil>}]
INFO: 2018/09/22 07:10:39 balancerWrapper: handle subconn state change: 0xc4201633b0, CONNECTING
INFO: 2018/09/22 07:10:39 ccBalancerWrapper: updating state and picker called by balancer: CONNECTING, 0xc42015cc00
WARNING: 2018/09/22 07:10:40 Failed to dial k81.hq-kube.com:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"; please retry.
WARNING: 2018/09/22 07:10:40 Failed to dial k81.hq-kube.com:2379: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"; please retry.
INFO: 2018/09/22 07:10:40 balancerWrapper: handle subconn state change: 0xc4201633b0, TRANSIENT_FAILURE
INFO: 2018/09/22 07:10:40 ccBalancerWrapper: updating state and picker called by balancer: TRANSIENT_FAILURE, 0xc42015cc00
INFO: 2018/09/22 07:10:40 balancerWrapper: handle subconn state change: 0xc4201633b0,
SHUTDOWN
INFO: 2018/09/22 07:10:40 ccBalancerWrapper: updating state and picker called by balancer: TRANSIENT_FAILURE, 0xc42015cc00`

I have tried every combination of --cert --certca --key params on etcdctl passing in various certificates generated by the bootkube generate assets step and nothing seems to work.

on face value the etcd-member service appears to be running fine:

`systemctl status etcd-member
  etcd-member.service - etcd (System Application Container)
   Loaded: loaded (/usr/lib/systemd/system/etcd-member.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/etcd-member.service.d
           └─40-etcd-cluster.conf
   Active: active (running) since Sat 2018-09-22 06:37:50 UTC; 34min ago
     Docs: https://github.com/coreos/etcd
  Process: 2012 ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid (code=exited, status=0/SUCCESS)
  Process: 2009 ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos (code=exited, status=0/SUCCESS)
 Main PID: 2025 (etcd)
    Tasks: 13 (limit: 32767)
   Memory: 32.6M
   CGroup: /system.slice/etcd-member.service
           └─2025 /usr/local/bin/etcd

Sep 22 06:37:50 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 06:37:50.019352 I | embed: ready to serve client requests
Sep 22 06:37:50 k81.hq-kube.com systemd[1]: Started etcd (System Application Container).
Sep 22 06:37:50 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 06:37:50.021580 I | embed: serving client requests on [::]:2379
Sep 22 07:02:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:02:34.370295 I | mvcc: store.index: compact 336
Sep 22 07:02:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:02:34.370901 I | mvcc: finished scheduled compaction at 336 (took 319.284µs)
Sep 22 07:07:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:07:34.375540 I | mvcc: store.index: compact 403
Sep 22 07:07:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:07:34.376090 I | mvcc: finished scheduled compaction at 403 (took 253.445µs)
Sep 22 07:10:35 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:10:35.148617 W | wal: sync duration of 1.249286794s, expected less than 1s
Sep 22 07:12:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:12:34.380780 I | mvcc: store.index: compact 470
Sep 22 07:12:34 k81.hq-kube.com etcd-wrapper[2025]: 2018-09-22 07:12:34.381449 I | mvcc: finished scheduled compaction at 470 (took 291.217µs)`

Can anyone point us in the right direction?

**Comment by richard-chivers** [comment]
Ok, so i have solved the connection to etcd, and the cluster is healthy, the command i used was:
`sudo ETCDCTL_API=2 etcdctl  --endpoints https://k81.hq-kube.com:2379 --key-file etcd-client.key --ca-file etcd-client-ca.crt --cert-file etcd-client.crt cluster-health`

This still leaves me with the original problem where the cluster never seems to come up.

`Sep 22 07:06:38 k81.hq-kube.com kubelet-wrapper[2248]: W0922 07:06:38.234612 2248 cni.go:196] Unable to update cni config: No networks found in /etc/kubernetes/cni/net.d Sep 22 07:06:38 k81.hq-kube.com kubelet-wrapper[2248]: E0922 07:06:38.234732 2248 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

Any help much appreciated.

**Comment by dghubble** [comment]
Hey Richard. As you might guess, the manual examples aren't really getting iterated upon anymore (Kubernetes v1.8.5). I'm thinking they ought to be removed.

Matchbox examples just need to show how to provision multiple machines. I put these together 3 years ago (before we made Tectonic, got aquired, k8s being huge). But now maintaining a quality Kubernetes distribution has become an undertaking in its own right and managing/operating it is a whole industry.

I do still actively use Matchbox through the API using the Terraform examples, which just link to a spin off [project](https://github.com/poseidon/typhoon) that does focus on Kubernetes (and uses Matchbox in a familiar way). Fine if that's not your thing too.

**Comment by dghubble** [comment]
Also, those etcd journal logs don't look problematic for that era and the cni config error was/is a super common ephemeral state you'll see in logs. I'd guess there wasn't actually an etcd issue here and you probably wanted to tail bootkube logs and inspect how far along in bootstrapping you made it - like did the initial 3 bootstrap pods start (just inspecting with docker).

**Comment by dghubble** [comment]
Closing due to #759
