### ISSUE TITLE
Wipe previous data of coreos installation

### ISSUE THREAD

**Issue by lncan** [poseidon/matchbox#721]
Hi guys, i want to know that how can i wipe coreos's data installed. I add 'wipe_filesystem: true' line like this in bootkube-controller.yaml and bootkube-worker.yaml files in ignition folder like this:
filesystems:
    - name: root
      mount:
        device: "/dev/sda1"
        format: "ext4"
        wipe_filesystem: true
        create:
          force: true
          options:
            - "-LROOT"

But when i reinstall coreos, the old data not be wiped. Does anyone have solution about this issue? Thanks you.

**Comment by dghubble** [comment]
I think this was probably intended for https://github.com/coreos/ignition/. This looks like it was mixing `storage.disks` and `filesystems` blocks (see the Ignition [spec](https://coreos.com/ignition/docs/latest/configuration-v2_1.html))
