### ISSUE TITLE
* provider.matchbox: failed to create Matchbox client or connect to matchbox.example.com:8081: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by 13567436138** [poseidon/matchbox#732]
* provider.matchbox: failed to create Matchbox client or connect to matchbox.example.com:8081: tls: failed to find any PEM data in certificate input

**Comment by dghubble** [comment]
[Verify](https://github.com/coreos/matchbox/blob/master/Documentation/deployment.md#verify) you're serving with the gRPC API enabled and providing a valid client [certificate](https://github.com/coreos/matchbox/blob/master/Documentation/deployment.md#generate-tls-certificates). This is a user error.

**Comment by 13567436138** [comment]
i generate the cert with cert-gen command.but all the cn is the same include server and client.will this be a problem

**Comment by 13567436138** [comment]
i generate the cert with cert-gen command.but all the cn is the same include server and client.will this be a problem

**Comment by dghubble** [comment]
I don't think I understand your issue
