### ISSUE TITLE
Systemd unit file configuration on CentOS 7.7.

### ISSUE THREAD

**Issue by lebrisg** [poseidon/matchbox#792]
I installed matchbox 0.8.3 on a CentOS 7.7 server. The purpose was to install OpenShift v4 in bare-metal UPI mode.
Following the matchbox documentation, I put the matchbox.service unit file provided into the /etc/systemd/system directory. The service started fine but something didn't work as expected.
I had to troubleshoot the service because I couldn't get the asset files.
Finally, I had to comment the two following instructions (perhaps only one is required) to have the daemon provide the service:
#ProtectHome=yes
#ProtectSystem=full
Just for your information.

**Comment by dghubble** [comment]
Well thanks for the info

**Comment by dghubble** [comment]
If you can express it succinctly in a comment, feel free to send a PR.
