### ISSUE TITLE
Bad certificate while connecting to gRPC matchbox service

### ISSUE THREAD

**Issue by adamszmajdzinski** [poseidon/matchbox#802]
I'm trying to set up bare metal kubernetes on physical nodes using matchbox. I'm following [Getting started guide](https://coreos.com/matchbox/docs/latest/getting-started.html). I have dnmasq and matchbox v0.6.1 on a master node working as a systemd service. I use terraform-provider-matchbox v0.3.0 plugin which is stored under ~/.terraform.d/plugins. Matchbox vars are set matchbox_address=0.0.0.0:8080 matchbox_rpc_address=0.0.0.0:8081

The problem is I can't connect terraform to matchbox gRPC because of:
Jun 05 11:02:35 master matchbox[1257]: 2020/06/05 11:02:35 grpc: Server.Serve failed to complete security handshake from "192.168.1.10:44132": remote error: tls: bad certificate

I generated fresh certificates and validated them but nothing changed. I export SAN variable with export SAN=DNS.1=matchbox.example.com

I provide configuration files and debug output of terraform plan.
[output.log](https://github.com/poseidon/matchbox/files/4735590/output.log)
[groups.txt](https://github.com/poseidon/matchbox/files/4735595/groups.txt)
[terraform.txt](https://github.com/poseidon/matchbox/files/4735596/terraform.txt)

**Comment by dghubble** [comment]
From the Github Issue Template:

> READ: Issues are used to receive focused bug reports from users and to track planned future enhancements by the authors. Topics like support, debugging help, advice, and operation are out of scope and should not use issues.

Inspect your TLS certificate and settings https://matchbox.psdn.io/getting-started/
