### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by andrewrothstein** [poseidon/matchbox#807]
anything I can do to help cut a new release?

**Comment by dghubble** [comment]
Next release is likely some time in the fall to coincide with the new Terraform and a docs refresh. Is there something in particular you're unable to use until release?

**Comment by andrewrothstein** [comment]
the get-flatcar and get-fedora-core aren't bundled in the v0.8.3 tarballs.

**Comment by dghubble** [comment]
You can find the scripts in https://github.com/poseidon/matchbox/tree/master/scripts. A release will come at a future milestone.
