### ISSUE TITLE
terraform init wrong provider registry

### ISSUE THREAD

**Issue by gaborsinko** [poseidon/matchbox#811]
**Description**

in your example, terraform does not work... I think I messed up something

`git clone https://github.com/coreos/matchbox.git`
`cd ~/matchbox/examples/terraform/simple-install`
`terraform init`

`Initializing the backend...`
`....`
`Error: Failed to install provider`
``
`Error while installing hashicorp/matchbox: provider registry `
`registry.terraform.io does not have a provider named `
`registry.terraform.io/hashicorp/matchbox`

'terraform version'
'Terraform v0.13.2'

* OS: ubuntu 20.04, coreOS
* Release: commit 4fc57035583b2a7aece800401a319f90f02fbf58

99% that I made a mistake, but I didn't find a description on either your or the terraform page that would have brought their example to life. Thus, the use value of the example is not yes because it does not work.

Sincerely Gabor Sinko

**Comment by dghubble** [comment]
The examples in this repo are written for Terraform v0.11/v0.12 https://github.com/poseidon/matchbox/pull/804. You're trying to use Terraform v0.13 and need v0.12. The examples may change in the future.
