### ISSUE TITLE
Add machine "discovery"

### ISSUE THREAD

**Issue by dghubble** [poseidon/matchbox#99]
Discover unrecognized machines which attempt to network boot from `bootcfg`. Collect basic instance data as a `bootcfg` `Instance` or `Machine` resource.

This is valuable to expose to gRPC clients (UIs or CLIs) so a user can create groups which match discovered machine instances. For example, a UI might allow a discovered instance to be assigned to a `Profile` and create the `bootcfg` match `Group` via gRPC call.

Depends on #97

**Comment by dghubble** [comment]
Include state about whether a node has successfully been provisioned by `bootcfg` before, where success if defined by receiving a checkin from a unit on host, which can perform some checks.

**Comment by rothgar** [comment]
This sounds very familiar to [Foreman discovery](https://github.com/theforeman/foreman_discovery). Essentially it dynamically creates the ipxe boot file (or defaults to discovery) based on if the system already exists in the db. If not, it gets a [discovery image](https://github.com/theforeman/foreman-discovery-image) which is a stripped down fedora image with puppet for reporting hardware facts. The system stays in that state until set to provision from the ui/cli when it reboots and boots to the proper provisioning ipxe file.

**Comment by calvix** [comment]
Any updates on this functions? I think its related to this https://github.com/coreos/matchbox/blob/master/matchbox/cli/instance_list.go

It would be very usefull to have it.
